# Este es el nombre que verás en la pestaña 'Actions' de GitHub
name: Runner de Pruebas Automáticas

# ¿Cuándo se despierta este asistente? Cuando subas cambios (push)
on: [push]

# 🚀 ESTA ES LA SOLUCIÓN: Forzamos a GitHub a usar Node 24 para todas las acciones
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  trabajo-de-calidad:
    # El asistente usará una computadora con Linux (Ubuntu)
    runs-on: ubuntu-latest
    
    steps:
      # Primero: El asistente descarga tu código a su computadora virtual
      - name: Clonar código
        uses: actions/checkout@v5

      # Segundo: Instala Python (el lenguaje que usa Robot)
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Tercero: Instala las herramientas de Robot Framework
      - name: Instalar Librerías desde Requirements
        run: |
          python -m pip install --upgrade pip
          # El robot ahora lee exactamente lo que tú tienes en tu PC
          pip install -r requirements.txt

      # Cuarto: Ejecuta las pruebas de Robot Framework
      #- name: Correr Test de API
      #  run: robot robotframework/api/test_api.robot
      
      #- name: Correr Test de UI
      # Agregamos la variable para cambiar 'chrome' por 'headlesschrome'
      #  run: robot --variable NAVEGADOR:headlesschrome robotframework/web/test_web.robot
      
      - name: Ejecutar Suite Completa (API y UI)
        # Ejecutamos toda la carpeta 'robotframework' de un solo golpe
        # Pasamos la variable headlesschrome para que la parte Web no falle
        run: python -m robot --variable NAVEGADOR:headlesschrome robotframework/

      # Quinto: Guardamos los informes de pruebas para que puedas verlos después
      - name: Cargar Reportes de Robot Framework
      # Este paso se ejecutará siempre, incluso si las pruebas fallan
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reportes-automatizacion
          path: |
            log.html
            report.html
            output.xml